### ISSUE TITLE
Project Status?

### ISSUE THREAD

**Issue by LexiconCode** [chilimangoes/CasterUIAutomation_POC#1]
This project is needed desperately for Castor. 

Are you planning to work on the implementation?
@chilimangoes

**Comment by chilimangoes** [comment]
Unfortunately, I have a lot of projects going on right now, both personally and professionally, and this is pretty far down my priority list. I would be happy to help out, if someone else is willing to do some of the heavy lifting, but I just don't have the bandwidth to be the primary contributor to this. @Versatilus had expressed interest in working on this and I will gladly make anyone else a repo contributor who's interested in helping out. I think I have a fairly good high-level idea of what needs to be done and how to design the communication API with Caster, so I will try to get that documented in the wiki or something. (Most of it's buried in the Caster channel on Gitter from late 2016)

If you're interested, let me know and I'll add you as a contributor.

**Comment by LexiconCode** [comment]
While I'm interested I don't have the skills to contribute C#.
That being said, I am willing to fork money in the direction to get it done. Perhaps we could freelance portions of the project?

**Comment by chilimangoes** [comment]
Well, that's a possibility I hadn't considered. I know plenty of C# developers and if you'd like, I could ask around to see if one of them would be interested in doing a bit of freelance open source work. Or if you have another avenue for hiring freelancers that you'd prefer, that's fine too.

**Comment by LexiconCode** [comment]
I prefer to use your contacts. Figuring out cost and expectations is important. Hopefully a few other people might contribute financially as well. Thank you for working on the Wiki as that'll be a great place to frame the big picture and how the project should be structured.

**Comment by chilimangoes** [comment]
So I've been mulling this over for a couple days and I'm starting to think that maybe I'll just bite the bullet and try to crank this out. I think I could probably get this mostly done in a few weeks if I pause some of my other projects for a bit. At the very least, by that point, we would have a better idea what's left to do and where any money could be best spent, if needed. And if I'm not able to completely finish in that time, I might be able to get it to a place where some of the other Caster contributors would feel more able to jump in and help finish it or add missing features.

**Comment by LexiconCode** [comment]
That's awfully generous of you. Do what you can and we'll see what we can do. I definitely think it will give us a better picture of the structure of the project and ease plugging in contributors.

**Comment by chilimangoes** [comment]
A quick status update on this:

I spent the first weekend trying to get interaction with the UAC working and had nothing but frustration. I was able to start a process on the secure desktop, but couldn't use the Win32 APIs to interact with the UAC. I know it has to be possible because apps like TeamViewer and VNC do it, but there's next to zero information online and the information that does exist seems to be missing pieces. I decided to table the requirement of interacting with the UAC for later and focus on the API and interacting with elevated programs. The good news is that interacting with elevated programs seems to work fine, so I'm working on the API now.

Last weekend, I created a lightweight embedded HTTP server, reorganized the code and worked out an idea of what the API should look like. This weekend, I'm working on implementing the API parser for the Key action from Dragonfly and I hope to have that done pretty soon. Then I'll work on how to call the API from Caster/Dragonfly grammars. Fortunately, I think the Key action is the most complicated to implement, so once that's done, the rest should be fairly easy.
